code --install-extension akamud.vscode-theme-onedark
code --install-extension alexcvzz.vscode-sqlite
code --install-extension Angular.ng-template
code --install-extension apollographql.vscode-apollo
code --install-extension arcanis.vscode-zipfs
code --install-extension artdiniz.quitcontrol-vscode
code --install-extension atlassian.atlascode
code --install-extension BazelBuild.vscode-bazel
code --install-extension bradlc.vscode-tailwindcss
code --install-extension burkeholland.simple-react-snippets
code --install-extension cssho.vscode-svgviewer
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension dracula-theme.theme-dracula
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension esbenp.prettier-vscode
code --install-extension eyhn.vscode-vibrancy
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.code-runner
code --install-extension golang.go
code --install-extension GraphQL.vscode-graphql
code --install-extension GraphQL.vscode-graphql-execution
code --install-extension GraphQL.vscode-graphql-syntax
code --install-extension Gruntfuggly.todo-tree
code --install-extension hashicorp.terraform
code --install-extension jasonnutter.search-node-modules
code --install-extension jebbs.plantuml
code --install-extension johnpapa.Angular1
code --install-extension johnpapa.vscode-peacock
code --install-extension liviuschera.noctis
code --install-extension mathiasfrohlich.Kotlin
code --install-extension mikestead.dotenv
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-dotnettools.vscode-dotnet-runtime
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-mssql.data-workspace-vscode
code --install-extension ms-mssql.mssql
code --install-extension ms-mssql.sql-bindings-vscode
code --install-extension ms-mssql.sql-database-projects-vscode
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode.cpptools
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension ms-vsliveshare.vsliveshare-audio
code --install-extension naumovs.color-highlight
code --install-extension Orta.vscode-twoslash-queries
code --install-extension PKief.material-icon-theme
code --install-extension Prisma.prisma
code --install-extension redhat.java
code --install-extension redhat.vscode-commons
code --install-extension redhat.vscode-yaml
code --install-extension robinbentley.sass-indented
code --install-extension rust-lang.rust-analyzer
code --install-extension SimonSiefke.svg-preview
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension styled-components.vscode-styled-components
code --install-extension svelte.svelte-vscode
code --install-extension tinkertrain.theme-panda
code --install-extension unifiedjs.vscode-mdx
code --install-extension VisualStudioExptTeam.intellicode-api-usage-examples
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscode-icons-team.vscode-icons
code --install-extension wix.vscode-import-cost
code --install-extension xdebug.php-debug
code --install-extension zhuangtongfa.material-theme